name: Build python executables

on:
  push:
    branches: [jon/react-electron]
    paths:
      - "skellycam/**"
      - ".github/workflows/build_python_executables.yml"
      - "pyproject.toml"
      - "binaries/build_pyinstaller_executable.py"
      - "binaries/skellycam.spec"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ./.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libpulse0 libegl1

      - name: Set up virtual environment
        run: python -m venv .venv

      - name: Activate virtual environment (Windows)
        if: runner.os == 'Windows'
        run: .\.venv\Scripts\activate
      - name: Activate virtual environment (macOS/Linux)
        if: runner.os != 'Windows'
        run: source .venv/bin/activate

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install the project dependencies
        run: pip install -e .

      - name: Build the project
        run: python /build_pyinstaller_executable.py

      - name: Upload artifact (GUI)
        uses: actions/upload-artifact@v3
        with:
          name: skellycam-${{ matrix.os }}
          path: dist/
