name: Build

on:
  push:
    branches: [jon/react-electron]
    paths:
      - "skellycam/**"
      - ".github/workflows/build_python_executables.yml"
      - "pyproject.toml"
      - "poetry.lock"
      - "poetry.toml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        # see details (matrix, python-version, python-version-file, etc.)
        # https://github.com/actions/setup-python
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry shell && poetry update
      - name: Build the project
        run: poetry run pyinstaller